---
- name: Copy a good version of the hosts file to a server
  gather_facts: false
  hosts: 52.176.58.46

  tasks:
    - name: Copying good file
      copy:
        src: files/good_hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
        backup: yes

