---
- name: Copy a bad version of the hosts file to a server
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
  - copy:
    src: /var/lib/awx/public/files/bad_hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    backup: yes
